query AllRoles {
  roles {
    totalCount
    items {
      createdAt
      description
      id
      isActive
      name
      updatedAt
      rolePermissions {
        permissionName
        roleId
        permission {
          description
          name
        }
      }
    }
  }
}