query GetClients {
  clients(skip: null, take: null, where: null, order: null) {
    items {
      ceoFirstName
      ceoLastName
      companyAddress
      companyEmail
      companyLocation
      companyLogo
      logoBase64
      companyName
      companyPhone
      createdAt
      dateJoined
      id
      jobTitle
      linkedIn
      locationCoordinates
      postalCode
      logoMimeType
      registrationNumber
      updatedAt
      verificationStatus
      website
      jobs {
        clientId
        createdAt
        duties
        id
        jobHours
        jobType
        location
        numberOfRoles
        paymentType
        published
        requirements
        salaryPerAnnum
        startDate
        status
        title
        updatedAt
        assignments {
          assignedAt
          candidateId
          jobId
          status
          candidate {
            createdAt
            email
            experience
            id
            name
            phone
            skills
            updatedAt
            verified
          }
          job {
            clientId
            createdAt
            duties
            id
            status
            location
            jobType
            jobHours
            requirements
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    totalCount
  }
}